version: '3.7'

services:
    api_php:
        volumes:
            - ./api:/app/api:rw,cached

    api_nginx:
        volumes:
            - ./api/public:/app/api/public:ro

    database:
        ports: [ '5432:5432' ]

    app:
        ports: [ '3000:3000' ]
        volumes:
            - ./app:/app/app:rw,cached
            - /app/app/node_modules

    proxy:
        build:
            context: ./proxy
        depends_on:
            - app
            - api_nginx
        ports: [ '443:443', '8443:8443' ]
