version: '3.7'

services:
    api_php:
        env_file: ./api/.env
        image: ${CONTAINER_REGISTRY_BASE}/api_php
        build:
            context: ./api
            target: api_php
            cache_from:
                - ${CONTAINER_REGISTRY_BASE}/api_php
                - ${CONTAINER_REGISTRY_BASE}/api_nginx
        depends_on:
            - database

    api_nginx:
        image: ${CONTAINER_REGISTRY_BASE}/api_nginx
        ports: [ '${API_PORT}:80' ]
        build:
            context: ./api
            target: api_nginx
            cache_from:
                - ${CONTAINER_REGISTRY_BASE}/api_php
                - ${CONTAINER_REGISTRY_BASE}/api_nginx
        depends_on:
            - api_php

    database:
        image: postgres:11-alpine
        volumes: [ 'database-data:/var/lib/postgresql/data' ]
        environment:
            - POSTGRES_DB=pwapoc
            - POSTGRES_USER=pwapoc
            - POSTGRES_PASSWORD=pwapoc

    app:
        env_file: ./app/.env
        image: ${CONTAINER_REGISTRY_BASE}/app
        ports: [ '${APP_PORT}:3000' ]
        build:
            context: ./app
            cache_from:
                - ${CONTAINER_REGISTRY_BASE}/app

volumes:
    database-data: ~
