version: '3.7'

services:
    api_php:
        image: ${CONTAINER_REGISTRY_BASE}/api_php
        build:
            context: ./api
            target: api_php
            cache_from:
                - ${CONTAINER_REGISTRY_BASE}/api_php
                - ${CONTAINER_REGISTRY_BASE}/api_nginx
        depends_on:
            - database

    api_nginx:
        image: ${CONTAINER_REGISTRY_BASE}/api_nginx
        build:
            context: ./api
            target: api_nginx
            cache_from:
                - ${CONTAINER_REGISTRY_BASE}/api_php
                - ${CONTAINER_REGISTRY_BASE}/api_nginx
        depends_on:
            - api_php

    database:
        image: postgres:11-alpine
        environment:
            - POSTGRES_DB=pwapoc
            - POSTGRES_USER=pwapoc
            - POSTGRES_PASSWORD=pwapoc

    app:
        image: ${CONTAINER_REGISTRY_BASE}/app
        build:
            context: ./app
            cache_from:
                - ${CONTAINER_REGISTRY_BASE}/app

volumes:
    database-data: ~
