monolog:
    handlers:
        main:
            type:     buffer
            handler:  easylog
            level:    debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        easylog:
            type: service
            id:   EasyCorp\EasyLog\EasyLogHandler


services:
    EasyCorp\EasyLog\EasyLogHandler:
        arguments: ['php://stdout']
